title: Tian-
#logo: "/assets/images/logopking.png"
#description: High Energy Astrophysics; Neutrino; Gamma-ray; IceCube; LHAASO; Albrecht Dûrer
#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
#remote_theme: remote_theme: ledge-framework/jekyll
