title: Tianqi's Homepage
#logo: "/assets/images/logopking.png"
#description: High Energy Astrophysics; Neutrino; Gamma-ray; IceCube; LHAASO; Albrecht Dûrer
#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
#remote_theme: remote_theme: ledge-framework/jekyll
color_scheme: blue

#plugins:
#  - jekyll-feed

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
